spring:
  datasource:
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  config-location: classpath:mybatis-config.xml
